###
# MkDocs Configuration File.
#
# To build these docs, change to base of repository and run `mkdocs build` and
# docs will be build into site_dir variable value in this file.
#
# Alternatively, there is a script in the `scripts` folder for convenience.
###
site_name: PyFPDF
site_url: https://alexanderankin.github.io/pyfpdf/
repo_url: https://github.com/alexanderankin/pyfpdf
site_description: Simple PDF generation for Python (FPDF PHP port) [FORK]
docs_dir: mkdocs_docs
site_dir: docs/mkdocs_docs
use_directory_urls: false
edit_uri: edit/master/mkdocs_docs
theme: material
# markdown_extensions: [toc, fenced_code, markdown_i18n]
markdown_extensions: [toc, fenced_code]
pages:
- 'Project Home': 'index.md'
- 'Tutorial':     'Tutorial.md'
- 'Tutorial Translations':
  - 'Tutorial (Spanish translation)': 'Tutorial-es.md'
- 'FAQ':          'FAQ.md'
- 'Development':  'Development.md'
- 'Templates':    'Templates.md'
- 'Unicode':      'Unicode.md'
- 'ReferenceManual':
  - 'Reference Manual':    'ReferenceManual.md'
  - 'accept_page_break':   'reference/accept_page_break.md'
  - 'add_font':            'reference/add_font.md'
  - 'add_link':            'reference/add_link.md'
  - 'add_page':            'reference/add_page.md'
  - 'alias_nb_pages':      'reference/alias_nb_pages.md'
  - 'cell':                'reference/cell.md'
  - 'close':               'reference/close.md'
  - 'code39':              'reference/code39.md'
  - 'dashed_line':         'reference/dashed_line.md'
  - 'ellipse':             'reference/ellipse.md'
  - 'error':               'reference/error.md'
  - 'FPDF':                'reference/FPDF.md'
  - 'footer':              'reference/footer.md'
  - 'get_string_width':    'reference/get_string_width.md'
  - 'get_x':               'reference/get_x.md'
  - 'get_y':               'reference/get_y.md'
  - 'header':              'reference/header.md'
  - 'image':               'reference/image.md'
  - 'interleaved2of5':     'reference/interleaved2of5.md'
  - 'load_resource':       'reference/load_resource.md'
  - 'line':                'reference/line.md'
  - 'link':                'reference/link.md'
  - 'ln':                  'reference/ln.md'
  - 'multi_cell':          'reference/multi_cell.md'
  - 'open':                'reference/open.md'
  - 'output':              'reference/output.md'
  - 'page_no':             'reference/page_no.md'
  - 'rect':                'reference/rect.md'
  - 'set_author':          'reference/set_author.md'
  - 'set_auto_page_break': 'reference/set_auto_page_break.md'
  - 'set_compression':     'reference/set_compression.md'
  - 'set_creator':         'reference/set_creator.md'
  - 'set_doc_option':      'reference/set_doc_option.md'
  - 'set_display_mode':    'reference/set_display_mode.md'
  - 'set_draw_color':      'reference/set_draw_color.md'
  - 'set_fill_color':      'reference/set_fill_color.md'
  - 'set_font':            'reference/set_font.md'
  - 'set_font_size':       'reference/set_font_size.md'
  - 'set_keywords':        'reference/set_keywords.md'
  - 'set_left_margin':     'reference/set_left_margin.md'
  - 'set_line_width':      'reference/set_line_width.md'
  - 'set_link':            'reference/set_link.md'
  - 'set_margins':         'reference/set_margins.md'
  - 'set_right_margin':    'reference/set_right_margin.md'
  - 'set_stretching':      'reference/set_stretching.md'
  - 'set_subject':         'reference/set_subject.md'
  - 'set_text_color':      'reference/set_text_color.md'
  - 'set_title':           'reference/set_title.md'
  - 'set_top_margin':      'reference/set_top_margin.md'
  - 'set_x':               'reference/set_x.md'
  - 'set_xy':              'reference/set_xy.md'
  - 'set_y':               'reference/set_y.md'
  - 'text':                'reference/text.md'
  - 'write':               'reference/write.md'
  - 'write_html':          'reference/write_html.md'
